//! Curated table of major world cities → IANA zone. Grouped by zone so the
//! mappings stay auditable. Many large cities (Atlanta, Boston, Seattle, …) have
//! no IANA zone of their own, so a name→zone table is the only way to resolve
//! them. Names are uppercase; the first match in query ranking (exact → prefix →
//! substring) wins, so more common cities are listed earlier within a region.
//!
//! A unit test asserts every zone here exists in jiff's bundled tzdb.

/// (DISPLAY NAME, IANA zone).
pub const CITIES: &[(&str, &str)] = &[
    // --- UTC / reference ---
    ("UTC", "UTC"),

    // ================= NORTH AMERICA =================
    // US Eastern — America/New_York
    ("NEW YORK", "America/New_York"),
    ("BROOKLYN", "America/New_York"),
    ("QUEENS", "America/New_York"),
    ("WASHINGTON", "America/New_York"),
    ("WASHINGTON DC", "America/New_York"),
    ("ATLANTA", "America/New_York"),
    ("BOSTON", "America/New_York"),
    ("MIAMI", "America/New_York"),
    ("PHILADELPHIA", "America/New_York"),
    ("BALTIMORE", "America/New_York"),
    ("CHARLOTTE", "America/New_York"),
    ("JACKSONVILLE", "America/New_York"),
    ("ORLANDO", "America/New_York"),
    ("TAMPA", "America/New_York"),
    ("PITTSBURGH", "America/New_York"),
    ("CINCINNATI", "America/New_York"),
    ("CLEVELAND", "America/New_York"),
    ("COLUMBUS", "America/New_York"),
    ("DETROIT", "America/Detroit"),
    ("BUFFALO", "America/New_York"),
    ("ROCHESTER", "America/New_York"),
    ("RICHMOND", "America/New_York"),
    ("VIRGINIA BEACH", "America/New_York"),
    ("RALEIGH", "America/New_York"),
    ("DURHAM", "America/New_York"),
    ("NEWARK", "America/New_York"),
    ("JERSEY CITY", "America/New_York"),
    ("PROVIDENCE", "America/New_York"),
    ("HARTFORD", "America/New_York"),
    ("LOUISVILLE", "America/Kentucky/Louisville"),
    ("LEXINGTON", "America/New_York"),
    ("INDIANAPOLIS", "America/Indiana/Indianapolis"),
    ("SYRACUSE", "America/New_York"),
    ("ALBANY", "America/New_York"),
    // US Central — America/Chicago
    ("CHICAGO", "America/Chicago"),
    ("HOUSTON", "America/Chicago"),
    ("DALLAS", "America/Chicago"),
    ("SAN ANTONIO", "America/Chicago"),
    ("AUSTIN", "America/Chicago"),
    ("FORT WORTH", "America/Chicago"),
    ("MEMPHIS", "America/Chicago"),
    ("NASHVILLE", "America/Chicago"),
    ("NEW ORLEANS", "America/Chicago"),
    ("OKLAHOMA CITY", "America/Chicago"),
    ("TULSA", "America/Chicago"),
    ("KANSAS CITY", "America/Chicago"),
    ("OMAHA", "America/Chicago"),
    ("MILWAUKEE", "America/Chicago"),
    ("MINNEAPOLIS", "America/Chicago"),
    ("SAINT PAUL", "America/Chicago"),
    ("SAINT LOUIS", "America/Chicago"),
    ("ST LOUIS", "America/Chicago"),
    ("WICHITA", "America/Chicago"),
    ("DES MOINES", "America/Chicago"),
    ("LITTLE ROCK", "America/Chicago"),
    ("BATON ROUGE", "America/Chicago"),
    ("MADISON", "America/Chicago"),
    ("BIRMINGHAM", "America/Chicago"),
    ("MONTGOMERY", "America/Chicago"),
    ("CORPUS CHRISTI", "America/Chicago"),
    ("LUBBOCK", "America/Chicago"),
    ("PLANO", "America/Chicago"),
    // US Mountain — America/Denver / Phoenix
    ("DENVER", "America/Denver"),
    ("EL PASO", "America/Denver"),
    ("ALBUQUERQUE", "America/Denver"),
    ("COLORADO SPRINGS", "America/Denver"),
    ("SALT LAKE CITY", "America/Denver"),
    ("SANTA FE", "America/Denver"),
    ("BOISE", "America/Boise"),
    ("CHEYENNE", "America/Denver"),
    ("BILLINGS", "America/Denver"),
    ("PHOENIX", "America/Phoenix"),
    ("TUCSON", "America/Phoenix"),
    ("MESA", "America/Phoenix"),
    ("SCOTTSDALE", "America/Phoenix"),
    ("CHANDLER", "America/Phoenix"),
    // US Pacific — America/Los_Angeles
    ("LOS ANGELES", "America/Los_Angeles"),
    ("SAN DIEGO", "America/Los_Angeles"),
    ("SAN JOSE", "America/Los_Angeles"),
    ("SAN FRANCISCO", "America/Los_Angeles"),
    ("FRESNO", "America/Los_Angeles"),
    ("SACRAMENTO", "America/Los_Angeles"),
    ("LONG BEACH", "America/Los_Angeles"),
    ("OAKLAND", "America/Los_Angeles"),
    ("BAKERSFIELD", "America/Los_Angeles"),
    ("ANAHEIM", "America/Los_Angeles"),
    ("SANTA ANA", "America/Los_Angeles"),
    ("RIVERSIDE", "America/Los_Angeles"),
    ("IRVINE", "America/Los_Angeles"),
    ("SEATTLE", "America/Los_Angeles"),
    ("PORTLAND", "America/Los_Angeles"),
    ("SPOKANE", "America/Los_Angeles"),
    ("TACOMA", "America/Los_Angeles"),
    ("LAS VEGAS", "America/Los_Angeles"),
    ("RENO", "America/Los_Angeles"),
    // US Alaska / Hawaii
    ("ANCHORAGE", "America/Anchorage"),
    ("FAIRBANKS", "America/Anchorage"),
    ("JUNEAU", "America/Juneau"),
    ("HONOLULU", "Pacific/Honolulu"),
    ("HILO", "Pacific/Honolulu"),
    // Canada
    ("TORONTO", "America/Toronto"),
    ("MONTREAL", "America/Toronto"),
    ("OTTAWA", "America/Toronto"),
    ("MISSISSAUGA", "America/Toronto"),
    ("HAMILTON", "America/Toronto"),
    ("QUEBEC CITY", "America/Toronto"),
    ("VANCOUVER", "America/Vancouver"),
    ("VICTORIA", "America/Vancouver"),
    ("SURREY", "America/Vancouver"),
    ("CALGARY", "America/Edmonton"),
    ("EDMONTON", "America/Edmonton"),
    ("WINNIPEG", "America/Winnipeg"),
    ("HALIFAX", "America/Halifax"),
    ("REGINA", "America/Regina"),
    ("SASKATOON", "America/Regina"),
    ("ST JOHNS", "America/St_Johns"),
    // Mexico / Central America / Caribbean
    ("MEXICO CITY", "America/Mexico_City"),
    ("GUADALAJARA", "America/Mexico_City"),
    ("PUEBLA", "America/Mexico_City"),
    ("LEON", "America/Mexico_City"),
    ("MONTERREY", "America/Monterrey"),
    ("TIJUANA", "America/Tijuana"),
    ("CANCUN", "America/Cancun"),
    ("PANAMA CITY", "America/Panama"),
    ("GUATEMALA CITY", "America/Guatemala"),
    ("SAN SALVADOR", "America/El_Salvador"),
    ("HAVANA", "America/Havana"),
    ("SANTO DOMINGO", "America/Santo_Domingo"),
    ("SAN JUAN", "America/Puerto_Rico"),
    ("KINGSTON", "America/Jamaica"),

    // ================= SOUTH AMERICA =================
    ("SAO PAULO", "America/Sao_Paulo"),
    ("RIO DE JANEIRO", "America/Sao_Paulo"),
    ("BRASILIA", "America/Sao_Paulo"),
    ("BELO HORIZONTE", "America/Sao_Paulo"),
    ("SALVADOR", "America/Bahia"),
    ("FORTALEZA", "America/Fortaleza"),
    ("CURITIBA", "America/Sao_Paulo"),
    ("RECIFE", "America/Recife"),
    ("PORTO ALEGRE", "America/Sao_Paulo"),
    ("MANAUS", "America/Manaus"),
    ("BUENOS AIRES", "America/Argentina/Buenos_Aires"),
    ("CORDOBA", "America/Argentina/Cordoba"),
    ("ROSARIO", "America/Argentina/Cordoba"),
    ("MENDOZA", "America/Argentina/Mendoza"),
    ("SANTIAGO", "America/Santiago"),
    ("LIMA", "America/Lima"),
    ("BOGOTA", "America/Bogota"),
    ("MEDELLIN", "America/Bogota"),
    ("CALI", "America/Bogota"),
    ("CARACAS", "America/Caracas"),
    ("QUITO", "America/Guayaquil"),
    ("GUAYAQUIL", "America/Guayaquil"),
    ("LA PAZ", "America/La_Paz"),
    ("MONTEVIDEO", "America/Montevideo"),
    ("ASUNCION", "America/Asuncion"),

    // ================= EUROPE =================
    ("LONDON", "Europe/London"),
    ("MANCHESTER", "Europe/London"),
    ("BIRMINGHAM UK", "Europe/London"),
    ("GLASGOW", "Europe/London"),
    ("EDINBURGH", "Europe/London"),
    ("LIVERPOOL", "Europe/London"),
    ("LEEDS", "Europe/London"),
    ("BRISTOL", "Europe/London"),
    ("CARDIFF", "Europe/London"),
    ("BELFAST", "Europe/London"),
    ("DUBLIN", "Europe/Dublin"),
    ("PARIS", "Europe/Paris"),
    ("MARSEILLE", "Europe/Paris"),
    ("LYON", "Europe/Paris"),
    ("TOULOUSE", "Europe/Paris"),
    ("NICE", "Europe/Paris"),
    ("BERLIN", "Europe/Berlin"),
    ("MUNICH", "Europe/Berlin"),
    ("FRANKFURT", "Europe/Berlin"),
    ("HAMBURG", "Europe/Berlin"),
    ("COLOGNE", "Europe/Berlin"),
    ("STUTTGART", "Europe/Berlin"),
    ("DUSSELDORF", "Europe/Berlin"),
    ("LEIPZIG", "Europe/Berlin"),
    ("MADRID", "Europe/Madrid"),
    ("BARCELONA", "Europe/Madrid"),
    ("VALENCIA", "Europe/Madrid"),
    ("SEVILLE", "Europe/Madrid"),
    ("MALAGA", "Europe/Madrid"),
    ("BILBAO", "Europe/Madrid"),
    ("ROME", "Europe/Rome"),
    ("MILAN", "Europe/Rome"),
    ("NAPLES", "Europe/Rome"),
    ("TURIN", "Europe/Rome"),
    ("PALERMO", "Europe/Rome"),
    ("FLORENCE", "Europe/Rome"),
    ("VENICE", "Europe/Rome"),
    ("BOLOGNA", "Europe/Rome"),
    ("AMSTERDAM", "Europe/Amsterdam"),
    ("ROTTERDAM", "Europe/Amsterdam"),
    ("THE HAGUE", "Europe/Amsterdam"),
    ("UTRECHT", "Europe/Amsterdam"),
    ("BRUSSELS", "Europe/Brussels"),
    ("ANTWERP", "Europe/Brussels"),
    ("VIENNA", "Europe/Vienna"),
    ("ZURICH", "Europe/Zurich"),
    ("GENEVA", "Europe/Zurich"),
    ("BASEL", "Europe/Zurich"),
    ("BERN", "Europe/Zurich"),
    ("LISBON", "Europe/Lisbon"),
    ("PORTO", "Europe/Lisbon"),
    ("PRAGUE", "Europe/Prague"),
    ("WARSAW", "Europe/Warsaw"),
    ("KRAKOW", "Europe/Warsaw"),
    ("LODZ", "Europe/Warsaw"),
    ("WROCLAW", "Europe/Warsaw"),
    ("BUDAPEST", "Europe/Budapest"),
    ("BUCHAREST", "Europe/Bucharest"),
    ("ATHENS", "Europe/Athens"),
    ("THESSALONIKI", "Europe/Athens"),
    ("STOCKHOLM", "Europe/Stockholm"),
    ("GOTHENBURG", "Europe/Stockholm"),
    ("OSLO", "Europe/Oslo"),
    ("COPENHAGEN", "Europe/Copenhagen"),
    ("HELSINKI", "Europe/Helsinki"),
    ("MOSCOW", "Europe/Moscow"),
    ("SAINT PETERSBURG", "Europe/Moscow"),
    ("ST PETERSBURG", "Europe/Moscow"),
    ("NIZHNY NOVGOROD", "Europe/Moscow"),
    ("KAZAN", "Europe/Moscow"),
    ("YEKATERINBURG", "Asia/Yekaterinburg"),
    ("NOVOSIBIRSK", "Asia/Novosibirsk"),
    ("VLADIVOSTOK", "Asia/Vladivostok"),
    ("KYIV", "Europe/Kyiv"),
    ("KIEV", "Europe/Kyiv"),
    ("KHARKIV", "Europe/Kyiv"),
    ("ODESA", "Europe/Kyiv"),
    ("LVIV", "Europe/Kyiv"),
    ("DNIPRO", "Europe/Kyiv"),
    ("ISTANBUL", "Europe/Istanbul"),
    ("ANKARA", "Europe/Istanbul"),
    ("IZMIR", "Europe/Istanbul"),
    ("BURSA", "Europe/Istanbul"),
    ("ANTALYA", "Europe/Istanbul"),
    ("BELGRADE", "Europe/Belgrade"),
    ("SOFIA", "Europe/Sofia"),
    ("ZAGREB", "Europe/Zagreb"),
    ("MINSK", "Europe/Minsk"),
    ("RIGA", "Europe/Riga"),
    ("VILNIUS", "Europe/Vilnius"),
    ("TALLINN", "Europe/Tallinn"),
    ("REYKJAVIK", "Atlantic/Reykjavik"),

    // ================= MIDDLE EAST =================
    ("DUBAI", "Asia/Dubai"),
    ("ABU DHABI", "Asia/Dubai"),
    ("SHARJAH", "Asia/Dubai"),
    ("DOHA", "Asia/Qatar"),
    ("RIYADH", "Asia/Riyadh"),
    ("JEDDAH", "Asia/Riyadh"),
    ("MECCA", "Asia/Riyadh"),
    ("MEDINA", "Asia/Riyadh"),
    ("DAMMAM", "Asia/Riyadh"),
    ("KUWAIT CITY", "Asia/Kuwait"),
    ("MANAMA", "Asia/Bahrain"),
    ("MUSCAT", "Asia/Muscat"),
    ("TEHRAN", "Asia/Tehran"),
    ("MASHHAD", "Asia/Tehran"),
    ("ISFAHAN", "Asia/Tehran"),
    ("BAGHDAD", "Asia/Baghdad"),
    ("BASRA", "Asia/Baghdad"),
    ("ERBIL", "Asia/Baghdad"),
    ("JERUSALEM", "Asia/Jerusalem"),
    ("TEL AVIV", "Asia/Jerusalem"),
    ("BEIRUT", "Asia/Beirut"),
    ("AMMAN", "Asia/Amman"),
    ("DAMASCUS", "Asia/Damascus"),

    // ================= AFRICA =================
    ("CAIRO", "Africa/Cairo"),
    ("ALEXANDRIA", "Africa/Cairo"),
    ("GIZA", "Africa/Cairo"),
    ("CASABLANCA", "Africa/Casablanca"),
    ("RABAT", "Africa/Casablanca"),
    ("MARRAKESH", "Africa/Casablanca"),
    ("LAGOS", "Africa/Lagos"),
    ("ABUJA", "Africa/Lagos"),
    ("KANO", "Africa/Lagos"),
    ("IBADAN", "Africa/Lagos"),
    ("NAIROBI", "Africa/Nairobi"),
    ("MOMBASA", "Africa/Nairobi"),
    ("JOHANNESBURG", "Africa/Johannesburg"),
    ("CAPE TOWN", "Africa/Johannesburg"),
    ("DURBAN", "Africa/Johannesburg"),
    ("PRETORIA", "Africa/Johannesburg"),
    ("SOWETO", "Africa/Johannesburg"),
    ("ACCRA", "Africa/Accra"),
    ("ADDIS ABABA", "Africa/Addis_Ababa"),
    ("DAR ES SALAAM", "Africa/Dar_es_Salaam"),
    ("ALGIERS", "Africa/Algiers"),
    ("TUNIS", "Africa/Tunis"),
    ("TRIPOLI", "Africa/Tripoli"),
    ("KHARTOUM", "Africa/Khartoum"),
    ("KAMPALA", "Africa/Kampala"),
    ("KINSHASA", "Africa/Kinshasa"),
    ("LUANDA", "Africa/Luanda"),
    ("DAKAR", "Africa/Dakar"),
    ("ABIDJAN", "Africa/Abidjan"),
    ("HARARE", "Africa/Harare"),

    // ================= SOUTH & CENTRAL ASIA =================
    ("KARACHI", "Asia/Karachi"),
    ("LAHORE", "Asia/Karachi"),
    ("ISLAMABAD", "Asia/Karachi"),
    ("RAWALPINDI", "Asia/Karachi"),
    ("FAISALABAD", "Asia/Karachi"),
    ("MULTAN", "Asia/Karachi"),
    ("PESHAWAR", "Asia/Karachi"),
    ("DELHI", "Asia/Kolkata"),
    ("NEW DELHI", "Asia/Kolkata"),
    ("MUMBAI", "Asia/Kolkata"),
    ("BANGALORE", "Asia/Kolkata"),
    ("BENGALURU", "Asia/Kolkata"),
    ("CHENNAI", "Asia/Kolkata"),
    ("KOLKATA", "Asia/Kolkata"),
    ("HYDERABAD", "Asia/Kolkata"),
    ("AHMEDABAD", "Asia/Kolkata"),
    ("PUNE", "Asia/Kolkata"),
    ("SURAT", "Asia/Kolkata"),
    ("JAIPUR", "Asia/Kolkata"),
    ("LUCKNOW", "Asia/Kolkata"),
    ("KANPUR", "Asia/Kolkata"),
    ("NAGPUR", "Asia/Kolkata"),
    ("KOCHI", "Asia/Kolkata"),
    ("CHANDIGARH", "Asia/Kolkata"),
    ("DHAKA", "Asia/Dhaka"),
    ("CHITTAGONG", "Asia/Dhaka"),
    ("KATHMANDU", "Asia/Kathmandu"),
    ("COLOMBO", "Asia/Colombo"),
    ("KABUL", "Asia/Kabul"),
    ("ALMATY", "Asia/Almaty"),
    ("ASTANA", "Asia/Almaty"),
    ("TASHKENT", "Asia/Tashkent"),
    ("BAKU", "Asia/Baku"),
    ("YEREVAN", "Asia/Yerevan"),
    ("TBILISI", "Asia/Tbilisi"),
    ("ULAANBAATAR", "Asia/Ulaanbaatar"),

    // ================= EAST & SOUTHEAST ASIA =================
    ("BEIJING", "Asia/Shanghai"),
    ("SHANGHAI", "Asia/Shanghai"),
    ("SHENZHEN", "Asia/Shanghai"),
    ("GUANGZHOU", "Asia/Shanghai"),
    ("CHENGDU", "Asia/Shanghai"),
    ("CHONGQING", "Asia/Shanghai"),
    ("TIANJIN", "Asia/Shanghai"),
    ("WUHAN", "Asia/Shanghai"),
    ("XIAN", "Asia/Shanghai"),
    ("HANGZHOU", "Asia/Shanghai"),
    ("NANJING", "Asia/Shanghai"),
    ("SHENYANG", "Asia/Shanghai"),
    ("HARBIN", "Asia/Shanghai"),
    ("QINGDAO", "Asia/Shanghai"),
    ("DALIAN", "Asia/Shanghai"),
    ("KUNMING", "Asia/Shanghai"),
    ("HONG KONG", "Asia/Hong_Kong"),
    ("MACAU", "Asia/Macau"),
    ("TAIPEI", "Asia/Taipei"),
    ("KAOHSIUNG", "Asia/Taipei"),
    ("TAICHUNG", "Asia/Taipei"),
    ("TOKYO", "Asia/Tokyo"),
    ("OSAKA", "Asia/Tokyo"),
    ("YOKOHAMA", "Asia/Tokyo"),
    ("NAGOYA", "Asia/Tokyo"),
    ("SAPPORO", "Asia/Tokyo"),
    ("FUKUOKA", "Asia/Tokyo"),
    ("KOBE", "Asia/Tokyo"),
    ("KYOTO", "Asia/Tokyo"),
    ("HIROSHIMA", "Asia/Tokyo"),
    ("SENDAI", "Asia/Tokyo"),
    ("SEOUL", "Asia/Seoul"),
    ("BUSAN", "Asia/Seoul"),
    ("INCHEON", "Asia/Seoul"),
    ("DAEGU", "Asia/Seoul"),
    ("DAEJEON", "Asia/Seoul"),
    ("GWANGJU", "Asia/Seoul"),
    ("BANGKOK", "Asia/Bangkok"),
    ("PHUKET", "Asia/Bangkok"),
    ("HANOI", "Asia/Ho_Chi_Minh"),
    ("HO CHI MINH CITY", "Asia/Ho_Chi_Minh"),
    ("SAIGON", "Asia/Ho_Chi_Minh"),
    ("JAKARTA", "Asia/Jakarta"),
    ("SURABAYA", "Asia/Jakarta"),
    ("BANDUNG", "Asia/Jakarta"),
    ("MEDAN", "Asia/Jakarta"),
    ("SINGAPORE", "Asia/Singapore"),
    ("KUALA LUMPUR", "Asia/Kuala_Lumpur"),
    ("GEORGE TOWN", "Asia/Kuala_Lumpur"),
    ("JOHOR BAHRU", "Asia/Kuala_Lumpur"),
    ("MANILA", "Asia/Manila"),
    ("QUEZON CITY", "Asia/Manila"),
    ("CEBU", "Asia/Manila"),
    ("DAVAO", "Asia/Manila"),
    ("YANGON", "Asia/Yangon"),
    ("PHNOM PENH", "Asia/Phnom_Penh"),
    ("VIENTIANE", "Asia/Vientiane"),

    // ================= OCEANIA =================
    ("SYDNEY", "Australia/Sydney"),
    ("CANBERRA", "Australia/Sydney"),
    ("NEWCASTLE", "Australia/Sydney"),
    ("MELBOURNE", "Australia/Melbourne"),
    ("GEELONG", "Australia/Melbourne"),
    ("BRISBANE", "Australia/Brisbane"),
    ("GOLD COAST", "Australia/Brisbane"),
    ("PERTH", "Australia/Perth"),
    ("ADELAIDE", "Australia/Adelaide"),
    ("DARWIN", "Australia/Darwin"),
    ("HOBART", "Australia/Hobart"),
    ("AUCKLAND", "Pacific/Auckland"),
    ("WELLINGTON", "Pacific/Auckland"),
    ("CHRISTCHURCH", "Pacific/Auckland"),
    ("SUVA", "Pacific/Fiji"),
    ("PORT MORESBY", "Pacific/Port_Moresby"),
];

#[cfg(test)]
mod tests {
    use super::CITIES;

    #[test]
    fn every_zone_is_valid() {
        let mut bad = Vec::new();
        for (name, zone) in CITIES {
            if jiff::tz::TimeZone::get(zone).is_err() {
                bad.push(format!("{name} -> {zone}"));
            }
        }
        assert!(bad.is_empty(), "unknown IANA zones: {bad:?}");
    }

    #[test]
    fn no_duplicate_names() {
        let mut names: Vec<&str> = CITIES.iter().map(|(n, _)| *n).collect();
        names.sort_unstable();
        let mut dups = Vec::new();
        for w in names.windows(2) {
            if w[0] == w[1] {
                dups.push(w[0]);
            }
        }
        assert!(dups.is_empty(), "duplicate city names: {dups:?}");
    }
}
